# Generated by Django 2.2.3 on 2019-10-07 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('grade', models.CharField(max_length=120)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Car')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Mechanic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
