# Generated by Django 2.2.3 on 2019-10-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Mechanic'),
        ),
    ]
