# Generated by Django 2.2.3 on 2019-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191014_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=4, default=50.25, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
