# Generated by Django 2.2.3 on 2019-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191015_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fee',
            field=models.DecimalField(decimal_places=4, default=(25.55), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanic',
            name='garage',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
