# Generated by Django 2.2.3 on 2019-10-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20191015_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=254, upload_to='profiles'),
        ),
    ]
