# Generated by Django 2.2.3 on 2019-10-17 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20191016_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
