# Generated by Django 2.2.3 on 2019-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20191017_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='image',
            field=models.CharField(default='profiles/1571171191411.jpg', max_length=160),
            preserve_default=False,
        ),
    ]
