# Generated by Django 2.2.3 on 2019-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20191023_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='license_image',
            field=models.ImageField(blank=True, max_length=254, upload_to='documents'),
        ),
    ]
