# Generated by Django 2.2.3 on 2019-10-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20191024_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
    ]
