# Generated by Django 2.2.3 on 2019-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_appointment_is_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fee',
            new_name='conventional_fee',
        ),
        migrations.AddField(
            model_name='car',
            name='grade_fee',
            field=models.DecimalField(decimal_places=2, default=30.25, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='medium_fee',
            field=models.DecimalField(decimal_places=2, default=32.55, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='premium_fee',
            field=models.DecimalField(decimal_places=2, default=145, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanic',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
