# Generated by Django 2.2.3 on 2019-10-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20191025_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
    ]
