# Generated by Django 2.2.3 on 2019-10-25 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_car_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
