# Generated by Django 2.2.3 on 2019-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20191025_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='instructions',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
