# Generated by Django 2.2.3 on 2019-10-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20191029_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
